name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - master  # or main, depending on your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # or your HTML folder like 'dist' or 'build'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
